name: Documentation
on:
  pull_request:
  merge_group:

env:
  DOXY_VER: '1.9.6'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref && github.ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Build_Doc:
    runs-on: ubuntu-20.04
    if: ${{ github.repository_owner == 'openvinotoolkit' }}
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          submodules: 'true'
          lfs: 'true'

      - name: Install apt-get dependencies
        uses: awalsh128/cache-apt-pkgs-action@a6c3917cc929dd0345bfb2d3feaf9101823370ad # v1.4.2
        with:
          packages: graphviz texlive liblua5.2-0 libclang1-9 libclang-cpp9
          version: 3.0

      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        id: cp310
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            docs/requirements.txt
            docs/openvino_sphinx_theme/setup.py

      - name: Install python dependencies
        run: |
          python3 -m pip install -r docs/requirements.txt
          (cd docs/openvino_sphinx_theme && python3 setup.py install)
          python3 -m pip install docs/openvino_custom_sphinx_sitemap

      - name: Download and install doxygen
        run: |
          # install doxygen
          wget https://www.doxygen.nl/files/doxygen-$DOXY_VER.linux.bin.tar.gz
          tar -xzf doxygen-$DOXY_VER.linux.bin.tar.gz
          echo "$(pwd)/doxygen-$DOXY_VER/bin/" >> $GITHUB_PATH

      - name: Validate benchmarks files
        run: |
          python3 docs/scripts/tests/validate_benchmarks.py  docs/sphinx_setup/_static/benchmarks_files/

      - name: Build docs
        run: |
          rm -rf build && mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_DOCS=ON
          cmake --build . --target sphinx_docs

      - name: Cache documentation
        id: cache_sphinx_docs
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: build/docs/_build/.doctrees
          key: sphinx-docs-cache

      - name: Archive docs HTML
        run: (cd build/docs && zip -r openvino_docs_html.zip _build)

      - name: Set PR number
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: 'Upload sphinx.log'
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: sphinx_build_log_${{ env.PR_NUMBER }}.log
          path: build/docs/sphinx.log

      - name: 'Upload docs html'
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: openvino_docs_html_${{ env.PR_NUMBER }}.zip
          path: build/docs/openvino_docs_html.zip

      - name: Run Pytest
        run: |
          pytest --sphinx="./build/docs/sphinx.log" \
                 --suppress-warnings="./docs/scripts/tests/suppress_warnings.txt" \
                 --confcutdir="./docs/scripts/tests/" \
                 --html="./build/docs/_artifacts/doc-generation.html" \
                 --sphinx-strip="$(pwd)/build/docs/sphinx_source" \
                 --xfail="./docs/scripts/tests/xfail.txt" \
                 --self-contained-html ./docs/scripts/tests/test_docs.py

      - name: 'Upload test results'
        if: failure()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: openvino_docs_pytest
          path: build/docs/_artifacts/
