name: Files Size
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Check_Files_Size:
    runs-on: ubuntu-22.04
    if: ${{ github.repository_owner == 'openvinotoolkit' }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: git ls-tree
        run: git ls-tree -r -t -l --full-name HEAD | sort -n -r -k 4

      - name: git lfs ls-files
        run: git lfs ls-files --size
