name: MO
on:
  push:
    paths:
      - 'tools/mo/**'
      - '.github/workflows/mo.yml'
    branches:
      - 'master'
      - 'releases/**'
  pull_request:
    paths:
      - 'tools/mo/**'
      - '.github/workflows/mo.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Pylint-UT:
    runs-on: ubuntu-22.04
    if: ${{ github.repository_owner == 'openvinotoolkit' }}
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('tools/mo/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          # For UT
          pip install unittest-xml-reporting==3.0.2
          # MO requirements
          pip install -r requirements_caffe.txt
          pip install -r requirements_kaldi.txt
          pip install -r requirements_onnx.txt
          pip install -r requirements_tf2.txt
          pip install -r requirements_dev.txt
        working-directory: tools/mo

      - name: Pylint-MO
        run: pylint -d C,R,W openvino/tools/mo
        working-directory: tools/mo
